### ISSUE TITLE
Executables for v1.1?

### ISSUE THREAD

**Issue by GH-User** [jeffaco/duplicacy-util#1]
Can we get executables for v1.1?
Thanks!

**Comment by jeffaco** [comment]
I show that `v1.1` was released 18 days ago. However, this issue was opened 9 days ago. @GH-User please clarify what it is that you're after.

By the way, FWIW, I was on a two week vacation. But still, two weeks is rather short to decide that a project is dead/abandoned, in my honest opinion.

Since `v1.1` binaries are indeed available, I'm closing this issue. Let me know if you need anything further, thanks.

**Comment by nriley** [comment]
Where are they available? They don't show up on the [Releases](https://github.com/jeffaco/duplicacy-util/releases) page for me — I just see "Source code" downloads rather than a bunch of platform-specific downloads like with 1.0.

**Comment by jeffaco** [comment]
Whoops, I see the problem. I tagged `v1.1` but then failed to post the binaries. [forehead slap]

I'll fix this now, one moment.

**Comment by jeffaco** [comment]
Binaries for `v1.1` have been posted, sorry for the oversight.
