### ISSUE TITLE
Error: exec: "duplicacy": executable file not found in %PATH%

### ISSUE THREAD

**Issue by GH-User** [jeffaco/duplicacy-util#13]
If I run the following command I'm getting this error:
`C:\_Duplicacy\_duplicacy-util\duplicacy-util.exe -version`
`Error: exec: "duplicacy": executable file not found in %PATH%`

Similar commands are working like this:
`C:\_Duplicacy\_duplicacy-util\duplicacy-util.exe -h`

**Comment by jeffaco** [comment]
I'm getting a slightly different response:

```
jeff$ duplicacy-util -version
21:30:54 Using global config: /Users/jeff/.duplicacy-util/duplicacy-util.yaml
Version: 1.3, Git Hash: d5e4b88
jeff$ 
```

I think what's happening is that I'm loading the global configuration file before checking for the version. Based on your output, you don't have a global configuration file. However, in order to address #7, part of loading the global configuration verifies that we can find "duplicacy" on the path since, ultimately, we'd need to run it to do our job.

For now, I'd suggest putting a global configuration file in place that specifies the path to the `duplicacy` program, like this:

```
duplicacypath: /Users/Jeff/Applications/duplicacy
```

This will allow `duplicacy-util` to find `duplicacy` and continue. Meanwhile, you shouldn't need a global configuration file just to do a `-version` command, so I'll patch `duplicacy-util` to process `-version` without loading the configuration file.

**Comment by jeffaco** [comment]
Change made, tested successfully. Merged to master branch after CI tests passed.
