### ISSUE TITLE
Feature request: Email function should also have an option to accept any SSL certificate

### ISSUE THREAD

**Issue by GH-User** [jeffaco/duplicacy-util#15]
Feature request: Email function should also have an option to accept any SSL certificate like a self signed cert. At the moment it only accepts certificates quite strict. Therefore I can't use my own email server that just uses self signed cert. Every email client has such an option and it would be great to have that here too.
Thanks!

**Comment by jeffaco** [comment]
So, to be clear, you're asking that the mail package just accept the certificate that the E-Mail server is offering and not verify it, right?

If so, it's easy to do that. However, there's a change in flight (issue #14) that is changing the format of the global initialization file slightly for mail configuration. It's a trivial editing change, but I have a preference of making the change AFTER #14 goes in, and thus only supporting this feature request (and any other new features) in the new format.

The full story is this:

* I decided that I set up the mail flags incorrectly in the global configuration file. Rather than prefixing all the email settings with `email`, they should have been in an email section (i.e. `email.*`). I noted that but didn't feel compelled to change it.

* Boudewijn (@boedy) graciously offered a pull request for duplicacy-util (in #14) for multiple notification channels (something that I've wanted too, but didn't get to). That's currently being worked on. He noted the error I made in email configuration, so he fixed it. We decided to accept old or new format for now, and deprecate the old format. But that code isn't in yet.

So here, I want to make a change (something like `email.acceptInsecureCertificate: true` would be in the global configuration file). Default would be to do what we do today, but if you set `acceptInsecureCertificate` to `true`, then we'll accept a self-signed certificate. The default should clearly be false for this.

Rather than support this in both the old and new formats, I'd rather just add this to the new format.

So, @GH-User this is easy to do. But would you mind waiting a few weeks (however long @boedy needs to finish up the framework for his new feature) before I made this change? If urgent for you, I'll work something out, but waiting a bit would make this somewhat easier for me (and avoids @boedy doing merges) if we wait a bit.

Let me know, thanks.

**Comment by GH-User** [comment]
Many thanks for your quick response!

> you're asking that the mail package just accept the certificate that the E-Mail server is offering and not verify it, right?

Yes, that's right.

> But would you mind waiting a few weeks before I made this change?

No problem at all to wait. At the moment I'm using a free SMTP relay service with a valid certificate for sending the emails as a workaround and it works well.

Thanks again!

**Comment by jeffaco** [comment]
Added new global configuration flag for this. Note that this is ONLY supported via the new configuration format. Instructions will be in the `1.4` release on how to change this, but briefly, the email settings in the global configuration setting should be something like this:

```
email:
  fromAddress: "Donald Duck <donald.xyzzy@gmail.com>"
  toAddress: "Donald Duck <donald.xyzzy@gmail.com>"
  serverHostname: smtp.gmail.com
  serverPort: 465
  authUsername: donald.xyzzy@gmail.com
  authPassword: gaozqlwbztypagwt
  acceptInsecureCerts: true
```

Only set this if you build from source or download `1.4`, once it's released.

`acceptInsecureCerts` is the setting that will allow self-signed certificates.

Closing this issue since it's resolved and pushed to master.
