### ISSUE TITLE
Add ability to store `emailAuthPassword` in environment variable

### ISSUE THREAD

**Issue by aboutte** [jeffaco/duplicacy-util#16]
I want to store my duplicacy-util.yml in version control but I can't do this until the `emailAuthPassword` is stored outside of this file.

**Comment by jeffaco** [comment]
Added environment variable `DU_EMAIL_AUTH_PASSWORD`; if this is defined, then it will override the value of `email.authPassword` from the global configuration.

This only works with a minor update to the global configuration file format (to be described with release `1.4`). If you wish to build from source, you can update the global configuration file as described in issue #15, and then this change will work.

Otherwise, wait for release `1.4` (probably to be released this weekend) and update your global configuration file at that time.

Be aware that `1.4` brings a new concept (notifications), and while the old configuration file format will still work for backwards compatibility, if you want new functionality, you must upgrade to the new format. The old format will be deprecated in `1.4` and, at some future date, will no longer be supported.

Closing this issue. Thanks for the suggestion.

**Comment by jeffaco** [comment]
One clarification: If you build from source to get this feature, do NOT set `acceptInsecureCerts: true` unless you need it. If email is working with you today without issue, then you don't need that.

I said to set that in the referenced issue because @GH-User did need it (that was the reason for the issue created). You probably do not need it.

**Comment by aboutte** [comment]
Just upgraded to 1.5 and `DU_EMAIL_AUTH_PASSWORD` is working great! Thanks!
