### ISSUE TITLE
Error: unable to obtain lock using lockfile

### ISSUE THREAD

**Issue by GH-User** [jeffaco/duplicacy-util#17]
I have created a task schedule (Windows 7) to start a duplicacy-util task every few hours to start a Duplicacy backup/copy task. Most of the time this task is already running because it runs quite long.

If the task is already running I'm getting this error message:

> Error: unable to obtain lock using lockfile: C:\Users\Username\.duplicacy-util\XyzID.lock

IMHO it shouldn't give an error like this because it's not really an error – it should just say that the task is already running.

The error email shows in Subject:

> duplicacy-util: Backup results for configuration XyzID (FAILURE)

I would like to filter these messages and auto-delete it but it's not possible because it just says "(FAILURE)".

**Comment by jeffaco** [comment]
You could filter by searching the body for `unable to obtain lock using lockfile:`. But I agree, this should be cleaner than that. Rather than failing, it should say something like:

> Warning: Backup already running and will be skipped

in the log file. And then the subject should be something like:

> duplicacy-util: Backup results for configuration XyzID (Skipped)

I'll take a look at this. It's a relatively easy change. My use case rarely has `duplicacy-util` stepping on itself, so this never struck me as a problem. But if you want to back up often, this would be a nice feature. And locking was important enough to me, up front, to design it in from the start.

Give me a bit, but I'll get to it.

**Comment by jeffaco** [comment]
Fixed with commit a43771e. Closing issue.
