### ISSUE TITLE
`-tn` always returns exit code 1

### ISSUE THREAD

**Issue by plasticrake** [jeffaco/duplicacy-util#28]
I'm writing a script to test if the notifications are setup and working. However when running `duplicacy-util -tn` it always returns an exit code of `1`. Is this by design? It would be nice if it could return an exit code of `0` if there were no issues. For now I'll write my script to see if stderr is empty which should do the same thing.

**Comment by jeffaco** [comment]
Okay, I took a look at this. Error handling was kinda not completely thought out in the new notification stuff, so I took care of that. Here's an output log (first a failure, then a success). Note that there are multiple errors because we send multiple messages, and each of them were failing.

```
$ vi ~/.duplicacy-util/duplicacy-util.yaml 
$ ./duplicacy-util -tn; echo $?            
16:09:44 Using global config: /Users/jeff/.duplicacy-util/duplicacy-util.yaml
Error: 535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials v5-v6sm18072151pfd.64 - gsmtp
Error: 535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials e193-v6sm17521042pfg.127 - gsmtp
Error: 535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials e193-v6sm17521042pfg.127 - gsmtp
Error: 535 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials l15-v6sm3455085pfi.187 - gsmtp
1
$ vi ~/.duplicacy-util/duplicacy-util.yaml 
$ ./duplicacy-util -tn; echo $?            
16:10:22 Using global config: /Users/jeff/.duplicacy-util/duplicacy-util.yaml
0
$
```

The basics here:

1. Run `vi` to change my password to something incorrect (easiest way to cause failure),
1. Run `duplicacy-uti -tn`; note non-zero exit status,
1. Run `vi` to fix my password,
1. Run `duplicacy-util`; note zero (success) exit status

I'll commit this shortly and close this issue.
