### ISSUE TITLE
Enter the path of the private key file:No private key file is provided

### ISSUE THREAD

**Issue by bodypilot** [jeffaco/duplicacy-util#29]
Running duplicay-util version 1.5 & duplicacy 2.1.1 on Linux Mint 18.3 (based on Ubuntu 16.04)

I'm testing automating my back-ups by doing a 

> crontab -e

and adding

`* * * * * /etc/cron.daily/duplicacy-util`
so it's running the duplicacy-util entry in cron.daily every minute.

duplicay-util in cron.daily looks like this
```
#!/bin/sh
/usr/local/bin/duplicacy-util -f LaptopHomefolder -a
```
Duplicacy-util logfile after being invoked like this:

> 19:30:01 Beginning backup on 10-19-2018 19:30:01
> 19:30:01 ######################################################################
> 19:30:01 Backing up to storage rp3-32 with 1 threads
> 19:30:01 Storage set to sftp://user@localserver:portnumber//mnt/data/backup/laptop
> 19:30:01 Enter the path of the private key file:No private key file is provided
> 19:30:01 Failed to load the SFTP storage at sftp://user@localserver:portnumber//mnt/data/backup/laptop: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
> 19:30:01 Error executing command: exit status 100

However, running duplicacy in the terminal yields the following result

> duplicacy backup
> Storage set to sftp://user@localserver:portnumber//mnt/data/backup/laptop
> Last backup at revision 14 found
> Indexing /home/gerjo
> Loaded 4 include/exclude pattern(s)
>etc
>etc
>Backup for /directory/ at revision 15 completed
>1 directory was not included due to access errors

so obviously duplicacy knows where to find my privat key.
Running duplicacy-util from the terminal makes this error even more perplexing as:

> duplicacy-util -f LaptopHomefolder -a
> 19:46:15 Using global config: /dir/.duplicacy-util/duplicacy-util.yaml
> 19:46:15 Using config file:   /dir/.duplicacy-util/LaptopHomefolder.yaml
> 19:46:15 duplicacy-util starting, version: 1.5, Git Hash: f2e7147
> 19:46:15 Rotating log files
> 19:46:15 Beginning backup on 10-19-2018 19:46:15
> 19:46:15 Backing up to storage rp3-32 with 1 threads
> 19:47:00   Files: 121473 total, 271,463M bytes; 67 new, 95,014K bytes
> 19:47:00   All chunks: 55485 total, 271,843M bytes; 16 new, 104,392K bytes, 40,303K bytes uploaded
> 19:47:00   Duration: 45 seconds
> 19:47:00 Pruning storage rp3-32 using 1 thread(s) -all
> 19:47:01 Checking storage rp3-32
> 19:47:37 Operations completed in 1:22

So no complaining about not finding a private key here. I have no idea what's going on here, please help me fix this.

**Comment by bodypilot** [comment]
Thinking about this some more I though that since cron.daily is executed as root and duplicacy (and duplicacy-util) has been set-up by a regular user (including the ssh keys) this might be a rights issue.

However doing a chmod 777 /regular_user/.ssh/id_rsa still results in the "Enter the path of the private key file:No private key file is provided" warning.

Setting up ssh keys under root and adding root's ssh key to the authorized_hosts file on the server doesn't help either.

**Comment by jeffaco** [comment]
I think you're along the right path. Duplicacy has a number of ways saving the password information, but they are always environment-based (i.e. user account, etc). If you switch user accounts, all bets are off.

For example, on Mac, Duplicacy uses the Mac OS/X keychain. If I'm logged out, the keychain is locked, and Duplicacy can't access it. So I stay logged in (keychain unlocked, but still need credentials to view it unless your application was previously allowed - thus the need to "set up" Duplicacy to not prompt for passwords). This is on Mac OS/X.

On Windows, there are other rules as well, particularly when dealing with remote volumes (since Windows has some rules to access those as well).

As for your problem, I see a number of problems right off the gate:

1. Just doing a `chmod 777 /regular_user/.ssh/id_rsa` won't help. If running under root, SSH will look for SSH keys under root, not under some random user.

1. As said above, Duplicacy secrets are stored per-user (it depends on what you're running for Linux; on my Linux, I don't have enough software installed for Duplicacy to store secrets, so it can't - I need to deal with it via environment variables or interactively).

To help alleviate your issues, I would consider some of the following:

1. Decide where you're going to run Duplicacy (what user), and stick with it. Be sure it's all set up properly. Don't try to run duplicacy-util under some different account.

1. Note that duplicacy-util is simply a tool to make running Duplicacy CLI easier. I'm 99% certain that if you didn't run duplicacy-util via cron, but ran Duplicacy itself, you'd get identical issues. This, this would serve to completely eliminate duplicacy-util as the cause. I'm not trying to "shunt" responsibility, I'll still try and help. But this may turn out to be a Duplicacy issue where you might need to raise this in the Duplicacy forum to get help over there from people that understand Duplicacy internals on Linux better than I (I uses Linux, but not routinely).

1. If worse comes to worse, you could store your secrets in environment variables if there's no other way. This is less than preferable (your secrets would be in plain text somewhere), but may turn out to be the easiest solution. Again, it depends on what you have running on Linux and how Duplicacy is actually storing the secrets.

Hopefully this gives you some ideas to look at. Let me know how it goes.

**Comment by bodypilot** [comment]
I'll set cron.daily up to run duplicacy, not duplicacy-util, and see what the results are.

It'll be a while before I return to this issue as I'm away from this computer for a couple of days. I'll report back as soon as I can.


-------- Origineel bericht --------
Van: Jeff Coffler <notifications@github.com>
Verzonden: 20 oktober 2018 18:00:24 CEST
Aan: jeffaco/duplicacy-util <duplicacy-util@noreply.github.com>
CC: bodypilot <gerjohultink@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [jeffaco/duplicacy-util] Enter the path of the private key file:No private key file is provided (#29)

I think you're along the right path. Duplicacy has a number of ways saving the password information, but they are always environment-based (i.e. user account, etc). If you switch user accounts, all bets are off.

For example, on Mac, Duplicacy uses the Mac OS/X keychain. If I'm logged out, the keychain is locked, and Duplicacy can't access it. So I stay logged in (keychain unlocked, but still need credentials to view it unless your application was previously allowed - thus the need to "set up" Duplicacy to not prompt for passwords). This is on Mac OS/X.

On Windows, there are other rules as well, particularly when dealing with remote volumes (since Windows has some rules to access those as well).

As for your problem, I see a number of problems right off the gate:

1. Just doing a `chmod 777 /regular_user/.ssh/id_rsa` won't help. If running under root, SSH will look for SSH keys under root, not under some random user.

1. As said above, Duplicacy secrets are stored per-user (it depends on what you're running for Linux; on my Linux, I don't have enough software installed for Duplicacy to store secrets, so it can't - I need to deal with it via environment variables or interactively).

To help alleviate your issues, I would consider some of the following:

1. Decide where you're going to run Duplicacy (what user), and stick with it. Be sure it's all set up properly. Don't try to run duplicacy-util under some different account.

1. Note that duplicacy-util is simply a tool to make running Duplicacy CLI easier. I'm 99% certain that if you didn't run duplicacy-util via cron, but ran Duplicacy itself, you'd get identical issues. This, this would serve to completely eliminate duplicacy-util as the cause. I'm not trying to "shunt" responsibility, I'll still try and help. But this may turn out to be a Duplicacy issue where you might need to raise this in the Duplicacy forum to get help over there from people that understand Duplicacy internals on Linux better than I (I uses Linux, but not routinely).

1. If worse comes to worse, you could store your secrets in environment variables if there's no other way. This is less than preferable (your secrets would be in plain text somewhere), but may turn out to be the easiest solution. Again, it depends on what you have running on Linux and how Duplicacy is actually storing the secrets.

Hopefully this gives you some ideas to look at. Let me know how it goes.

**Comment by bodypilot** [comment]
I'll set cron.daily up to run duplicacy, not duplicacy-util, and see what the results are.

It'll be a while before I return to this issue as I'm away from this computer for a couple of days. I'll report back as soon as I can.

**Comment by jeffaco** [comment]
Oh. Oops, missed this.

Also be aware that SSH is picky about permissions of it's keys. A private key file (like `/regular_user/.ssh/id_rsa`), in general, must be permitted to only the user. Otherwise, SSH will refuse to use it. This can be seen interactively with the debug flag to SSH when the private key file will be ignored if you try to use it to connect to some other host.

**Comment by plasticrake** [comment]
@bodypilot I also run this from root and the easiest way is to set `ssh_key_file` in the preferences file.

`duplicacy set -key ssh_key_file -value /home/<user>/.ssh/id_rsa`

Then no matter the user running it duplicacy will use the private key you want

https://forum.duplicacy.com/t/passwords-credentials-and-environment-variables/1094

**Comment by jeffaco** [comment]
@bodypilot Is this issue resolved for you? Can we close this issue?

**Comment by bodypilot** [comment]
Yes, I'm happy with this fix/workaround.
