### ISSUE TITLE
nothing happens (?)

### ISSUE THREAD

**Issue by anibalinbalin** [jeffaco/duplicacy-util#33]
I'm sure I'm doing something wrong but I can't see what it is. 
I downloaded the windows release and even made my own via installing go and compiling.
But the thing is that nothing happens when I open it. Smartscreen is disabled and I even tried in another box.
Via CMD I even get this weird msg:
![screenshot 2019-01-11 21 27 42](https://user-images.githubusercontent.com/6696725/51066359-702b6980-15e8-11e9-90c4-c5a036eeba38.png)

**Comment by jeffaco** [comment]
@anibalinbalin 

Be aware that `duplicacy-util` is a command line application, designed to run in the background (generally). It's not intended to launch and run as a Windows application. This means that you MUST run it via the command line (or PowerShell or some other shell of your choosing).

Furthermore, note that to run, `duplicacy-util` must be configured via a short configuration file. One of those configuration settings is the location of the storage directory (where to find it's configuration files). It's giving that error because `duplicacy-util` can't find it's configuration file (or repository to back up).

I suggest you read the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file, which gives instructions on how to configure `duplicacy-util`.

Let me know if you have further questions, thanks.
