### ISSUE TITLE
Running duplicacy-util_linux_x64_1.5 produces error

### ISSUE THREAD

**Issue by umlito** [jeffaco/duplicacy-util#34]
In Fedora 29, I'm trying to run duplicacy-util_linux_x64_1.5 by copying and renaming the file to `/usr/bin/duplicacy-util`, setting permissions with `chmod +x` then running the file with .`/duplicacy-util`. When I do this, I receive an error stating: `Error: Unable to resolve location for storage directory` and the program does not run. I currently have Duplicacy working. How might I be able to get duplicacy-util to run given this error?

**Comment by jeffaco** [comment]
This is identical to issue #33.

Note that to run, `duplicacy-util` must be configured via a short configuration file. One of those configuration settings is the location of the storage directory (where to find it's configuration files). It's giving that error because `duplicacy-util` can't find it's configuration file (or repository to back up).

I suggest you read the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file, which gives instructions on how to configure `duplicacy-util`.

Let me know if you have further questions, thanks.
