### ISSUE TITLE
Verbose/debug (-v -d flags) don't seem to pass -d flag to duplicacy

### ISSUE THREAD

**Issue by dygordon** [jeffaco/duplicacy-util#38]
Love the utility! I hope I'm not missing something but I am trying to troubleshoot an issue with keychain access when running as root from launchd and find myself needing the -d  output from duplicacy.

However when duplicacy-util is run with -v -d flags they don't seem to make it through to the duplicacy call. And using the quote field in the config file puts the -d flag after the backup command rather than before so that fails as well. 

Running on OS X.

**Comment by jeffaco** [comment]
Hmph, you're not missing a thing. The `-d` and `-v` qualifiers are intended for `duplicacy-util` itself, and not for `duplicacy`. Worse, while there is a mechanism to pass parameters to `duplicacy` (good thinking for catching that!), `duplicacy` is placement-sensitive in handling of command line options, and the `quote` feature doesn't allow for placing parameters at the beginning of the command line. In short: crud. You don't have the tools you need to do what you're trying to do without me adding a feature or you making a quick change to the source code to diagnose this.

Before you get too far into debugging, however, I'd look at issue #29 (which covers some of this). In short, run `duplicacy` itself from the account you're going to run from and, once that's working, then `duplicacy-util` should be able to run `duplicacy` as well.

Note that I run on Mac OS/X as well. I normally am logging in (and the computer display is off) when backups run in the middle of the night, so my keychain is unlocked (I run under my user account). This is important so that `duplicacy` can read things from the keychain if you store things there. I'm not sure if `cron` or `launchd` jobs unlock the keychain when they run under some other account. If they do not, then you may need to pass credentials via environment variables to `duplicacy` to get to things like your cloud credentials, encryption keys, etc.

I'd start with: Get `duplicacy` itself to run first. Then try and add `duplicacy-util` to the mix. That should "just work". Then, if scheduling fails, you know it's a keychain issue, and you know how to fix it (`launchd` lets you trivially set up environment variables, and you can do that with `cron` as well a little less directly).

If you do get `duplicacy` working interactively, and then `duplicacy-util` does not work interactively, reach out to me, and I'll support you in whatever way I can.

Let me know what you find, thanks!

**Comment by dygordon** [comment]
Thanks for the good thinking and help beyond what's in scope for duplicacy-util. I hadn't thought to just call duplicacy directly from launchd but obviously that's where to start.

I have got duplicacy and duplicacy-util working from the root account in console mode but yeah not sure what happens with the keychain from launchd. It seems from other things I've seen that it should be possible so I suppose we'll see!

And I will indeed a) let you know what I find; and, b) download and edit the source to pass the flag if it turns out I need it!

**Comment by dygordon** [comment]
It is definitely a Keychain issue which must be somewhat particular to how Duplicacy is trying to get the keys out, as it seems accessing the System keychain with launchd has worked for people in other cases. And I did ensure the keys are in there. 

But I am not going to burn any more time on it and will just put it all in the config files as they are all within the root account anyway.

**Comment by jeffaco** [comment]
I thought it might be the keychain.

I'm highly skeptical that the keychain is unlocked with `launchd`, only because as I understand it, it's not possible given Apple's security model (especially with changes over the past year or so). The keychain, by default, is encrypted with the user password. You don't need the user password to run a job via `launchd`. Thus, I don't see how it's possible that the keychain is unlocked with `launchd`, as the user password is not available in that case.

I stay logged in for a number of reasons:

1. I love that the Apple Watch will unlock my account, nice time saver,
2. Much faster to get going for a machine that I use a few minutes here and there (at times, anyway),
3. I need to back up a NAS, which is mounted as a remote server (per-user state), and
4. I want to store `duplicacy` credentials in the keychain, so I need the keychain to be unlocked.

What's important to this topic is 3 and 4 above. But even if I took 3 (above) out of the mix, I would expect that if I logged out, my jobs would start failing because `duplicacy` couldn't get at the credential in the keychain. Sounds like that's just where you are.

Anyway, glad you solved it. I'll close this issue for now. But by all means, if you have further questions or want to bounce ideas off me, feel free to re-open this and reach out

**Comment by dygordon** [comment]
Thanks Jeff. Just to update you, I did burn a bit more time on it and figured it out. ;)

You have to add the duplicacy keys to the System keychain to get this to work. And the duplicacy binary needs to be listed in the ACL for each key. This way nothing has to unlock the keychain, as the app can access it without a GUI prompt or password.

Critically, the UserName and SessionCreate keys can't be set in the plist or it won't work even with the keys in the System keychain, not sure why. I'd tried this initially thinking it would allow access to the Keychain but I suppose something in the environment or otherwise is different. 

So it's running as root and the .duplicacy-util directory is in /var/root.

Thanks again for your help!

**Comment by jeffaco** [comment]
Cool, glad you got it working. Thanks for reaching out, and for documenting your efforts here.
