### ISSUE TITLE
Nice project, but abandoned?

### ISSUE THREAD

**Issue by GH-User** [jeffaco/duplicacy-util#4]
Nice project, but unfortunately it looks like it is abandoned.

**Comment by jeffaco** [comment]
I'm not sure why I wasn't getting E-mail notification of issues here. But wow, a new release was posted 18 days ago, and @GH-User suggests that the project is abandoned? Why would you think that?

This project is certainly not abandoned - I use it daily and am completely open to implementing suggestions and new features.

Closing this issue since the project is not abandoned.

**Comment by GH-User** [comment]
Thanks a lot for this reply, and apology for my impatience. I falsely assumed it was abandoned because of no reply at all.

**Comment by jeffaco** [comment]
Yeah, I was on vacation at the time of your comment. Otherwise I would have responded immediately. Sorry for the confusion.
