### ISSUE TITLE
Support for on-site storage copy commands

### ISSUE THREAD

**Issue by akirusk** [jeffaco/duplicacy-util#44]
Is it possible to use duplicacy-util to perform the actions for copying backups from onsite storage to a cloud provider? From what I can tell, you can't currently run a copy command without also running a backup to a specified storage. See https://forum.duplicacy.com/t/back-up-to-multiple-storages/1075:

> It is also possible to run the copy command directly on your onsite storage server. All you need to do is to create a dummy repository there, and then initialize it with the same default storage (but as a local disk) and add the same additional storage:
> 
> Copy to clipboard
>  log in to your local storage server
> mkdir -p \path\to\dummy\repository
> cd \path\to\dummy\repository
> duplicacy init repository_id onsite_storage_url
> duplicacy add -copy default offsite_storage --bit-identical repository_id offsite_storage_url
> duplicacy copy -from default -to offsite_storage
> 
> This not only frees your work computer from running the copy command, but also speeds up the copy process, since now Duplicacy can read chunks from a local disk
> 
> (local_server -> router -> offsite_storage)
> instead of over the network
> (local server -> router -> your computer -> router -> offsite_storage).

**Comment by jeffaco** [comment]
No, that's not true. Please carefully review the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file. If you look at the [Command Line Usage](https://github.com/jeffaco/duplicacy-util/blob/master/README.md#command-line-usage), you'll note that `duplicacy-util` does support the -copy qualifier to just perform a copy operation.

Let me know if you have further questions, @akirusk. Otherwise, feel free to close this issue. Thanks!

**Comment by akirusk** [comment]
I think my confusion was in the local config file requiring a storage to be specified. Does seem to work fine using -copy with a filler for storage in the config, thanks for your assistance.
