### ISSUE TITLE
Email Notifications Question/Issue

### ISSUE THREAD

**Issue by baubaid** [jeffaco/duplicacy-util#47]
Hi,

Love this tool by the way!

I'm not sure if this is an issue or just simply a question. I've followed the instructions on the README, and everything seems to work as expected except for email notifications. I noticed that the `-m` flag is now deprecated, but I'm not sure what this means exactly for email notifications. Should they still be working (automatically, I guess)?

If they should be working, then I'm having an issue with them for some reason. I have configured my email and even successfully tested it using the `duplicacy-util -tn`, but when I execute the command `dupliacy-util -f config_file -a -q`, I do not receive any emails when the process is finished.

Am I missing something here?

Thanks!

**Comment by baubaid** [comment]
Update: A little odd, but seems to be working right now. Not sure what the problem was.

While I'm here, can I ask if there's any way to change the subjects of the emails I receive? I would love to be able to know if the backup was a success or a failure at a glance. At the moment, the status is the last word in the e-mail subject and, at least with my e-mail client, not visible immediately. Having the status at the beginning of the subject line would help immensely.

Thanks again!

**Comment by baubaid** [comment]
Update: I think I've figured out what the problem was. I did not choose to store my email password in the configuration file, and wanted instead to retrieve it via the command line from Keychain. I thought adding these instructions in my `.zshrc` file would be sufficient to make things work, but as it turns out, it was sufficient to get `duplicacy-util` to work from the command line, but not sufficient for `launchd`. I'm a bit of a noob, but I guess I would have to load in the password in the plist file for it to have access to it(?).

As a workaround, I just created a bash script with the password instructions followed by the command to run `duplicacy-util`, pointed the plist file to that instead, and everything works like a charm now! As an added bonus, I can easily get desktop notifications using `terminal-notifier` this way in addition to the email address.

Feel free to close this; I'll leave it open just in case.

**Comment by jeffaco** [comment]
Hi @baubaid, hope I can answer your questions. You asked a lot of questions, so if I missed anything, please reach back to me.

First, I strongly recommend you take a look at [Management of E-Mail Messages](https://github.com/jeffaco/duplicacy-util#management-of-e-mail-messages) in my [README](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file, it has a lot of really useful information (so I've been told anyway, and it accurately reflects what I do).

1. E-Mail notifications are automatic if e-mail is configured in the global configuration file. There's really no reason to NOT send e-mail (if you have it configured), so I removed the options to make this happen (actually, to be more forthcoming, a contributor did when he reworked that code to be more extendable).

1. If you fail to get an E-Mail message and email notification is configured, you should see an error in your log files. It would be quite odd to get an error that wasn't in your logs. Did you look at your log files when that happened? What did it say?

1. The keychain on the Mac is a funny beast. It's much more than just a place to store passwords. It's a fully encrypted container to store all sorts of items (passwords is just one thing that it stores). Note that the "key" to unlock this, normally, is your account password. If you're not logged in, the keychain will be locked, and I don't believe it's possible for a scheduled job to get access to the keychain in this mode. Note that, the way that I use duplicacy, it gets storage encryption keys and the such via the keychain. In order to make sure that the keychain is unlocked, I leave my account logged in (I don't log out), just putting the monitor to sleep (and you need a password to unlock the computer, but I am logged in). This allows duplicacy to look up stuff in the keychain to its hearts content. When you looked at this and noted the failures, were you logged out or in at this point? If logged in, I would expect that a remote job would be able to access the keychain, just as duplicacy itself can.

1. I am super anal about security. It's rare (probably like "never") that I come across someone as anal as I am. All my passwords are encrypted with a password manager, my average password is 64 bytes of random characters (if the site allows it). For less secure sites, I always pick passwords as long as the site allows, always completely random. My password manager password itself is quite long (45 or 50 bytes - something like that). I never, ever reuse passwords for multiple accounts or multiple WWW sites. I always use two-factor authentication (if available). And, if I can, I don't have a password at all (favoring a secure encrypted SSH key since it's 2FA - you have the key, you know the passphrase - except I don't know the passphrase, the password manager does - it's long and random too). Because of this, I created an gmail account (accounts are free) for the sole purpose of sending e-mail in duplicacy-util. This e-mail account, since literally nothing in it, has very little to lose if it's compromised (although I do the basics and it's 2FA protected with an application key to allow me to send mail). Thus, I do put the password in my global configuration file, but the file is protected against other users, and if someone were to get it, all they could do with it is send e-mail.

1. There is currently no way to change the subject line of the e-mail message. You're the first one that has asked for that. Can you make the window wider so you can see the subject? If you followed my advice in [Management of E-Mail Messages](https://github.com/jeffaco/duplicacy-util#management-of-e-mail-messages), the end of the line wouldn't be important anyway since you'd only be looking at failure messages in your inbox. But if this is important to you, I'd be happy to take a PR that implemented this. Storing a format string in the global configuration, and reading that before sending messages, would be a straight-forward to do.

I wasn't aware of [terminal-notifier](https://github.com/julienXX/terminal-notifier), I think that's what you meant. I've been thinking it would be nice to support this capability natively from duplicacy-util. So for me, I'd be more interested in something like [Beeep](https://github.com/gen2brain/beeep), which looks like it would easily allow me to send cross-platform alerts directly from duplicacy-util. I'll need to put this on my to-do list when I do more work on duplicacy-util.

I think I've answered all your questions. Let me know if you have further questions!

**Comment by baubaid** [comment]
Thanks for the comprehensive response! Really appreciate you taking the time to answer my questions and flesh things out.

> 2. If you fail to get an E-Mail message and email notification is configured, you should see an error in your log files. It would be quite odd to get an error that wasn't in your logs. Did you look at your log files when that happened? What did it say?

As I remember it, the duplicacy-util log file didn't have any unusual errors. The backup completes successfully and that's where the duplicacy-util log file ends. When I started outputting log/error files from the plist file, that's when I saw an authentication error and realized it must be the email password. I spent hours tinkering and trying different workarounds until I got it to work, so apologies it's all sort of blending in together in my mind right now.

> 3. The keychain on the Mac is a funny beast. It's much more than just a place to store passwords. It's a fully encrypted container to store all sorts of items (passwords is just one thing that it stores). Note that the "key" to unlock this, normally, is your account password. If you're not logged in, the keychain will be locked, and I don't believe it's possible for a scheduled job to get access to the keychain in this mode. Note that, the way that I use duplicacy, it gets storage encryption keys and the such via the keychain. In order to make sure that the keychain is unlocked, I leave my account logged in (I don't log out), just putting the monitor to sleep (and you need a password to unlock the computer, but I am logged in). This allows duplicacy to look up stuff in the keychain to its hearts content. When you looked at this and noted the failures, were you logged out or in at this point? If logged in, I would expect that a remote job would be able to access the keychain, just as duplicacy itself can.

I was logged in. Just to clarify, the backup part was fine and like you said, duplicacy seamlessly gets its password from Keychain and I didn't have to worry about that part. It was the email password that I had issues with since I chose not to store it in the configuration file.

> 4. I am super anal about security. It's rare (probably like "never") that I come across someone as anal as I am. All my passwords are encrypted with a password manager, my average password is 64 bytes of random characters (if the site allows it). For less secure sites, I always pick passwords as long as the site allows, always completely random. My password manager password itself is quite long (45 or 50 bytes - something like that). I never, ever reuse passwords for multiple accounts or multiple WWW sites. I always use two-factor authentication (if available). And, if I can, I don't have a password at all (favoring a secure encrypted SSH key since it's 2FA - you have the key, you know the passphrase - except I don't know the passphrase, the password manager does - it's long and random too). Because of this, I created an gmail account (accounts are free) for the sole purpose of sending e-mail in duplicacy-util. This e-mail account, since literally nothing in it, has very little to lose if it's compromised (although I do the basics and it's 2FA protected with an application key to allow me to send mail). Thus, I do put the password in my global configuration file, but the file is protected against other users, and if someone were to get it, all they could do with it is send e-mail.

That's fair. I hadn't thought of creating a Gmail account solely for these backups but I think that's a very reasonable idea. It also means I can use the script for cleaning up old logs which is quite handy.

5. There is currently no way to change the subject line of the e-mail message. You're the first one that has asked for that. Can you make the window wider so you can see the subject? If you followed my advice in Management of E-Mail Messages, the end of the line wouldn't be important anyway since you'd only be looking at failure messages in your inbox. But if this is important to you, I'd be happy to take a PR that implemented this. Storing a format string in the global configuration, and reading that before sending messages, would be a straight-forward to do.

Yeah, I realize that it's a bit of a weird request. I was just wondering if that was an option as you seem to have thought of all sorts of configurations and it would make my life easier. I'm still testing both duplicacy and duplicacy-util so I currently have it set up so that all types of status emails are sent and would love to just deal with them quickly if they're success emails. But I agree that once I'm confident that everything is working, I can do away with success messages and just have failure emails show up (also terminal-notifier should help with that).

I'm not familiar with Go, otherwise I would be happy to submit a PR for this -- as you said, it should be straightforward from a conceptual point of view. For now, I have found the strings in the code and edited them so that the status comes first in the subject line, and then rebuilt the binary. Now, it's all good.

I was unaware of Beeep, but that sounds like a great idea. Appreciate your work and time!

**Comment by jeffaco** [comment]
I don't have the complete picture, so it's hard for me to fully identify what was happening. It sounds like you were using some sort of script to try and fetch the mail server password and then make it available to `duplicacy-util` via the environment variable. If that's the case, then an error in the script would be found by debugging the script, as you did.

If, instead, the error was within `duplicacy-util`, then that software should have logged it. If it didn't, please replicate so I can fix that! I had an error recently (actually made me laugh) in which `duplicacy-util`, while trying to send a (successful) backup notification via e-mail, ran into a transient error. That caused the mail interface to return an error, which caused `duplicacy-util` to change the state from success to error. All this was in the log (and in the actual e-mail message as well). So `duplicacy-util` then tried to send email for a failure. This time, the transient error did not occur, and the mail transmission was successful. I come along in the morning, see there was a failure, and in looking at the log, saw that the backup was 100% successful and it just had a transient error while sending the (success) message. I never saw this before (so it's rare). I laughed out loud (literally) and deleted the message.

As for the e-mail password, I put that in the configuration file because dealing with getting it on various platforms securely (presumably security registry on Windows, keychain on Mac, I dunno on Linux) was non-trivial. So I punted it. Since I set up e-mail the way I did, I didn't care (much) about security of the e-mail server, so that was good enough for me. People never complained, so I never really looked back. If you worked out your scripting, though, to properly fetch the e-mail password (even from a launchd job), and assigned it to the appropriate environment variable, this would have worked (I actually unit test that in my code). Another user did that and asked for the environment variable for that reason, and I made that change.

I use gmail for my mail. As a result, success messages go straight to trash (see the filtering I set up in email, explained in the `README.md` file), and trash automatically gets deleted in 30 days. Or, said another way, with the filtering set up, no e-mail management is necessary. It takes care of itself for cleaning up the messages.

I actually used `duplicacy-util` as a launch-board to learn Go. If you wanted to learn, this would be a very easy PR. Pulling things from global config is super-easy (see code that already exists). Then do simple string replacements for things like the job name, job status, etc. Then use that for the subject instead of the default subject. Shouldn't take long at all, might be a good way to get your feet wet if you felt like learning Go! :smile:  

Hope this was helpful. Let me know if you have further questions. If not, feel free to close this issue. Thanks for reaching out!

**Comment by baubaid** [comment]
> If you worked out your scripting, though, to properly fetch the e-mail password (even from a launchd job), and assigned it to the appropriate environment variable, this would have worked (I actually unit test that in my code). Another user did that and asked for the environment variable for that reason, and I made that change.

That was basically what I was trying to do, but I did a poor job of passing it on to the environment variable in the beginning.

> I actually used duplicacy-util as a launch-board to learn Go. If you wanted to learn, this would be a very easy PR. Pulling things from global config is super-easy (see code that already exists). Then do simple string replacements for things like the job name, job status, etc. Then use that for the subject instead of the default subject. Shouldn't take long at all, might be a good way to get your feet wet if you felt like learning Go! 😄

I might look into this in the near future if I have some time. I agree that it shouldn't be complicated and I could figure things out on the fly.

Thanks for this discussion! I'll close it now.
