### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by mdombro** [jeffaco/duplicacy-util#6]
This program looks perfect for what I'm looking for!

I just have two questions - and I apologize in advance if I'm just being dense and not seeing the answer.

1. Do you have to first initialize the directories for duplicacy? Or will this script take care of that? I imagine you do, and also do it to set up the cloud storage passwords and such...

2. Can you specify multiple directories to back up in a single local yaml config file? I probably need to read the Duplicacy docs some more, just not 100% sure on what the `repository` value does in the local config yaml file.

Thanks for doing this project - it looks like some great work!

**Comment by jeffaco** [comment]
Hi @mdombro 

Yeah, `duplicacy-util` expects that `duplicacy` is "set up" properly ahead of time. I was thinking of adding a section about how to do that in the README file, but haven't gotten to that yet. I'll leave this issue open as a reminder to take care of that, thanks!

Since `duplicacy-util` as no knowledge of backup repository passwords, you need to set up `duplicacy` so that password prompts won't happen. If password prompts do happen, `duplicacy-util` can't answer them, and the backup will abort.

To set up the backup for initial use, there is [documentation](https://github.com/mattjm/duplicacy-script) that @mattjm worked up that was pretty decent. That said, these are the basic steps I followed to initialize backing up Quicken, one of my repositories:

```
duplicacy init -e -storage-name b2 quicken b2://<bucket-name>
duplicacy add -e -copy b2 azure quicken azure://<bucket-name>      # Copy
duplicacy add -e azure-direct quicken-direct azure:<bucket-name> # Direct

duplicacy backup -storage b2 -stats -threads 10
duplicacy backup -storage azure-direct -stats -threads 5
duplicacy copy -from b2 -to azure -stats -threads 10
```

This initialized the repository and set it up for backup to both `Backblaze` and `Azure`. It also performed the first backup, taking care of final password prompts. I suggest you study the [Duplicacy Wiki](https://github.com/gilbertchen/duplicacy/wiki) carefully, the documentation is pretty good.

As for your second question: You can not currently specify multiple backup directories in a single YAML configuration file. I tried this myself (back when I was backing up two things together; I have since separated them out), and had problems. De-duplication did take care of it, but because of de-duplication, the log file was quite long and noisy. As a result, I ended up setting up links to the two repositories. I had something like this:

```
~/jeff/backup-repository
~/jeff/backup-repository/<link-to-first-repo>
~/jeff/backup-repository/<link-to-second-repo>
```

Then I specified `~/jeff/backup-respository` as my backup repository, and all was well. While this did work well, I ultimately decided that two totally separate repositories should live in separate buckets and specified that. That worked for me since, in general, buckets are "free", and you are charged solely for the storage utilized by your repositories. If that's in one bucket or ten buckets, it doesn't much matter.

That said, if you try multiple repositories against a single bucket, and it works well for you, I'd be happy to add that capability to `duplicacy-util`. Just open a new issue and let me know. Meanwhile, the documentation here should be enough for you to get started, and I'll resolve this issue once I improve the README documentation on how to get started.

I hope this was useful to you. If you have further questions, please feel free to reach out.

**Comment by mdombro** [comment]
Yes, this was extremely useful, thank you!
I'll definitely poke around more in the duplicacy docs to get a better feel of what can be done. I did end up getting everything to work last night, but I still need to set up copying to a second storage. Your example here should actually help quite a bit in that. And the overall background info is great to know.

Again, thanks for making this project open, it should come in super handy.

**Comment by jeffaco** [comment]
I added some "getting started" documentation in commit 9b51e38. Resolving this issue.
